name: OpaleFaction
version: '${project.version}'
main: fr.opaleuhc.opalefaction.OpaleFaction
author: Opale
api-version: 1.19
description: OpaleFaction
website: https://opaleuhc.fr
softdepend:
  - LuckPerms
  - DecentHolograms
  - PlayerNPC
commands:
  f:
    description: Commande principale du plugin
    aliases:
      - faction
      - fac
      - f
    permission: opalefaction.faction
    permission-message: Vous n'avez pas la permission d'utiliser cette commande
  spawn:
    description: Commande pour se téléporter au spawn
    permission: opalefaction.spawn
    permission-message: Vous n'avez pas la permission d'utiliser cette commande
  shop:
    description: Commande pour ouvrir le shop
    permission: opalefaction.shop
    permission-message: Vous n'avez pas la permission d'utiliser cette commande
    aliases:
      - shop
  money:
    description: Commande pour voir son argent
    permission: opalefaction.money
    permission-message: Vous n'avez pas la permission d'utiliser cette commande
    aliases:
      - argent
      - balance
  pay:
    description: Commande pour payer un joueur
    permission: opalefaction.pay
    permission-message: Vous n'avez pas la permission d'utiliser cette commande
  baltop:
    description: Commande pour voir le top des joueurs les plus riches
    permission: opalefaction.baltop
    permission-message: Vous n'avez pas la permission d'utiliser cette commande
    aliases:
      - topmoney
      - balancetop
      - bt